import {
  BASE_UP,
  PHONE_PORTRAIT_UP,
  POST_IPHONE6_PORTRAIT_UP,
  POST_IPHONE6_PLUS_PORTRAIT_UP,
  PHONE_LANDSCAPE_UP,
  SMALL_DEVICES_LANDSCAPE_UP,
  BETWEEN_SMALL_DEVICES_TABLET_UP,
  TABLET_PORTRAIT_UP,
  TABLET_LANDSCAPE_UP,
  DESKTOP_UP
} from "./breakpoints";
import { MONTHS, WEEKDAYS } from "./date";
import { LAYER_HEIGHT as PARALLAX_LAYER_HEIGHT } from "./parallax";

const MIN_WIDTH_BREAKPOINTS = [
  BASE_UP,
  PHONE_PORTRAIT_UP,
  POST_IPHONE6_PORTRAIT_UP,
  POST_IPHONE6_PLUS_PORTRAIT_UP,
  PHONE_LANDSCAPE_UP,
  SMALL_DEVICES_LANDSCAPE_UP,
  BETWEEN_SMALL_DEVICES_TABLET_UP,
  TABLET_PORTRAIT_UP,
  TABLET_LANDSCAPE_UP,
  DESKTOP_UP
];

export { MIN_WIDTH_BREAKPOINTS, MONTHS, WEEKDAYS, PARALLAX_LAYER_HEIGHT };
